### ISSUE TITLE
while running i am getting error like this

### ISSUE THREAD

**Issue by MJSneha** [ibizabroker/library-management-system#1]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Apr 07 00:02:16 IST 2023
There was an unexpected error (type=Unauthorized, status=401).
Unauthorized

**Comment by ibizabroker** [comment]
@MJSneha you can't create the first admin user using the UI. Use an API tool like Postman to add a base admin user.

Just select POST mapping and use the default url `http://localhost:8080/users`, you can use the sample data that I've provided below. This will create an admin user with username: user and password: password.
```
{
    "username": "user",
    "name": "First User",
    "password": "password",
    "role": [
        {
            "roleName": "Admin"
        }
    ]
}
```

**Comment by MJSneha** [comment]
Thank you so much
