### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Pushpa8802** [ibizabroker/library-management-system#2]
Plz provide sql code or else tell that which tables are created in mysql.
Books and borrow tables are enough

**Comment by ibizabroker** [comment]
Hi @Pushpa8802 
The tables will automatically get created in your mysql, update your mysql username and password in [application properties](https://github.com/ibizabroker/library-management-system/blob/master/lms-backend/src/main/resources/application.properties). The tables which will get created in your mysql are mentioned in the [entity](https://github.com/ibizabroker/library-management-system/tree/master/lms-backend/src/main/java/com/ibizabroker/lms/entity) folder. 
I would suggest using the UI to fill the tables, create an admin user using an API tool like Postman.
POST map it to `http://localhost:8080/users`, use the below data in body as a json to create a user with `username: admin` and `password: admin`.
```json
{
    "username": "admin",
    "name": "First Admin",
    "password": "admin",
    "role": [
        {
            "roleName": "Admin"
        }
    ]
} 
```

**Comment by Pushpa8802** [comment]
I execute in eclipse as maven project but it shows errors

**Comment by ibizabroker** [comment]
Can you elaborate the error?

**Comment by Pushpa8802** [comment]
It executed successfully after adding letters and setters on .java files 

Finally it opens login page but it asks username provided by the library admin.
Here i'm unable to login can u please help me with this one issue

**Comment by ibizabroker** [comment]
Follow the first comment, hit a POST request on `http://localhost:8080/users` with the json provided. That will create the admin user.

**Comment by Pushpa8802** [comment]
Okay,Thankyou soo muchh for helping

**Comment by Pushpa8802** [comment]
Can u please explain me to post a request on postman bcz I got 401
unauthorized error

Plz help me with this.Plz don't mind I will disturb you these many times.
