### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pushpa8802** [ibizabroker/library-management-system#3]
{"timestamp":"2024-03-06T06:18:51.720+00:00","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/users"} i got this error while i send a request on postman

**Comment by ibizabroker** [comment]
@Pushpa8802 you can create an admin user directly through mysql once the tables are created

**Comment by Pushpa8802** [comment]
On which table I can insert admin username and password
Everything works well except that login page plz help me with this.It is an urgent work for me.plz try to understand
